---
- name: Register with Satellite
  tags:
    - register
    - satellite
    - subscription
  redhat_subscription:
    activationkey: "{{ satellite_activationkey }}"
    org_id: "{{ satellite_org_id }}"
    pool_ids: "{{ satellite_pool_ids | default(omit) }}"
    force_register: "{{ satellite_force_register | default(false) }}"
    auto_attach: yes
    state: present
  register: register_system
  until: register_system is not failed
  retries: 5

# purge option doesn't exist until ansible 2.8
# so we enable the repos here and disable the ones we don't need afterward
- name: Enable RHSM repositories
  tags:
  - repos_enable
  - satellite
  rhsm_repository:
    name: "{{ rhsm_repos }}"
    state: present
  register: rhsm_state_enable
  until: rhsm_state_enable is not failed
  retries: 15

- name: Disable unnecessary RHSM repositories
  tags:
  - repos_disable
  - satellite
  rhsm_repository:
    name: "{{ rhsm_state_enable.repositories | map(attribute='id') | difference(rhsm_repos) }}"
    state: disabled
  register: rhsm_state_disable
  until: rhsm_state_disable is not failed
  retries: 15
